"""add commission_base and company_margin to Deal

Revision ID: 12011f601836
Revises: 7c1beeea76e5
Create Date: 2025-10-19 10:39:30.982202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12011f601836'
down_revision = '7c1beeea76e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_base', sa.String(length=20), nullable=False, server_default='profit'))
        batch_op.add_column(sa.Column('company_margin', sa.Float(), nullable=False, server_default='30.0'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_column('company_margin')
        batch_op.drop_column('commission_base')

    # ### end Alembic commands ###
