"""Increase password hash length

Revision ID: 229b1f477c53
Revises: 3b1f051dcb67
Create Date: 2025-09-01 18:31:03.683195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229b1f477c53'
down_revision = '3b1f051dcb67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
