"""Add margin and commission to user model

Revision ID: 7c1beeea76e5
Revises: 229b1f477c53
Create Date: 2025-09-09 14:11:29.843993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1beeea76e5'
down_revision = '229b1f477c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_margin', sa.Float(), nullable=False, server_default='30.0'))
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=False, server_default='40.0'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('company_margin')

    # ### end Alembic commands ###
