"""add status to Lead

Revision ID: dd2b50c9b8f1
Revises: 12011f601836
Create Date: 2025-10-20 09:49:15.334106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2b50c9b8f1'
down_revision = '12011f601836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('lead', schema=None) as batch_op:
    batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='New'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
